import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

import { MomentsView } from '../apps/wechat/moments-view.js';
import { WechatData } from '../apps/wechat/wechat-data.js';

const indexSource = fs.readFileSync(new URL('../index.js', import.meta.url), 'utf8');
const momentsViewSource = fs.readFileSync(new URL('../apps/wechat/moments-view.js', import.meta.url), 'utf8');

function createWechatData(moments) {
    const data = Object.create(WechatData.prototype);
    data.data = {
        chats: [],
        messages: {},
        moments,
        walletByChat: {},
        walletTransactions: []
    };
    data._messagesDirty = {};
    data.getMessages = () => [];
    data._cleanupManagedImagesForDeletedMessages = () => {};
    data._rollbackWalletTransactions = () => false;
    data.saveData = () => {};
    data._notifyUnreadChanged = () => {};
    return data;
}

function withVirtualPhone(run) {
    const originalWindow = globalThis.window;
    globalThis.window = { VirtualPhone: {} };
    try {
        return run();
    } finally {
        if (originalWindow === undefined) delete globalThis.window;
        else globalThis.window = originalWindow;
    }
}

test('exact floor replacement removes only moments generated by that Tavern floor', () => withVirtualPhone(() => {
    const data = createWechatData([
        { id: 'older', fromMainChatTag: true, tavernMessageIndex: 7 },
        { id: 'target', fromMainChatTag: true, tavernMessageIndex: 8 },
        { id: 'future', fromMainChatTag: true, tavernMessageIndex: 9 },
        { id: 'manual' }
    ]);

    assert.equal(data.removeMainChatTagMessagesAtFloor(8), true);
    assert.deepEqual(data.data.moments.map(moment => moment.id), ['older', 'future', 'manual']);
}));

test('deleting a Tavern floor removes generated future moments but preserves manual posts', () => withVirtualPhone(() => {
    const data = createWechatData([
        { id: 'older', fromMainChatTag: true, tavernMessageIndex: 7 },
        { id: 'deleted-floor', fromMainChatTag: true, tavernMessageIndex: 8 },
        { id: 'later-floor', fromMainChatTag: true, tavernMessageIndex: 9 },
        { id: 'manual-contact-refresh' },
        { id: 'manual-user-post', name: '用户' }
    ]);

    assert.equal(data.rollbackToFloor(8), true);
    assert.deepEqual(
        data.data.moments.map(moment => moment.id),
        ['older', 'manual-contact-refresh', 'manual-user-post']
    );
}));

test('contact moments expose the same single-delete control as user moments', () => {
    const view = Object.create(MomentsView.prototype);
    view.app = {
        wechatData: {},
        renderAvatar: () => '<span class="avatar"></span>'
    };
    view.getContactAvatar = () => '👤';
    view._renderEmojiText = text => text;

    const html = view.renderMomentItem({
        id: 'contact-moment',
        name: '联系人',
        text: '联系人发布的朋友圈',
        images: [],
        likeList: [],
        commentList: []
    });

    assert.match(html, /class="moment-delete-btn"/);
    assert.match(html, /data-moment-id="contact-moment"/);
    assert.match(momentsViewSource, /querySelectorAll\('\.moment-item'\)\.forEach/);
    assert.doesNotMatch(momentsViewSource, /\.moment-item\[data-own-moment="1"\]/);
});

test('the Tavern deletion hook rolls back WeChat data and refreshes an open phone', () => {
    const start = indexSource.indexOf('if (context.event_types.MESSAGE_DELETED)');
    const end = indexSource.indexOf('if (context.event_types.GENERATION_STARTED)', start);
    assert.ok(start >= 0 && end > start, 'message deletion hook should be present');
    const deletionHook = indexSource.slice(start, end);

    assert.match(deletionHook, /new module\.WechatData\(storage\)/);
    assert.match(deletionHook, /rollbackToFloor\?\.\(deletedFloor\)/);
    assert.match(deletionHook, /activeWechatApp\.render\(\)/);
});
